name: "Marek Łuszczki's site"
markdown: kramdown
theme: jekyll-theme-cayman
title: "Marek Łuszczki"
description: "Hello there!"
show_downloads: false
permalink: /blog/:year/:month/:day/:title
url: https://maktel.github.io
owner: "Marek Łuszczki"
github_url: https://github.com/Maktel

prose:
	metadata:
    	_posts:
			- name: "theme"
            field:
				element: "hidden"
				value: "post"