name: Marek Łuszczki's site
markdown: kramdown
theme: jekyll-theme-cayman
title: Basement of Doom
description: Marek Łuszczki
show_downloads: false
permalink: /blog/:year/:month/:day/:title
url: https://maktel.github.io
