name: "Marek Łuszczki's site"
markdown: kramdown
theme: jekyll-theme-cayman
title: "Marek Łuszczki"
description: "Hello there!"
show_downloads: false
permalink: /blog/:year/:month/:day/:title
url: https://maktel.github.io
owner: "Marek Łuszczki"
github_url: https://github.com/Maktel

prose:
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
      - name: "theme"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Categories"
          alterable: true
          options:
            - name: "Linux"
              value: "linux"
            - name: "ReactJS"
              value: "reactjs"
            - name: "Javascript"
              value: "javascript"
